[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
opinion_market = "2NaUpg4jEZVGDBmmuKYLdsAfSGKwHxjghhfgVpQvZJYu"

[programs.devnet]
opinion_market = "2NaUpg4jEZVGDBmmuKYLdsAfSGKwHxjghhfgVpQvZJYu"

[programs.testnet]
opinion_market = "2NaUpg4jEZVGDBmmuKYLdsAfSGKwHxjghhfgVpQvZJYu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/hsuthi/phantom_deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
