[package]
name = "opinion-market"
version = "0.1.0"
description = "Opinion Market Protocol â€” Sentiment Layer for Prediction Markets"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "opinion_market"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = { version = "0.32.1", features = ["token"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
